ALTER TYPE "PaymentStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';
ALTER TYPE "TransactionType" ADD VALUE IF NOT EXISTS 'INVOICE_CANCELLATION_CREDIT';
ALTER TYPE "TransactionType" ADD VALUE IF NOT EXISTS 'PAYMENT_CANCELLATION_DEBIT';
ALTER TYPE "SupplierPurchaseStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';
ALTER TYPE "SupplierTransactionType" ADD VALUE IF NOT EXISTS 'PURCHASE_CANCELLATION';
